name = "webring-ca"
main = "src/index.tsx"
compatibility_date = "2025-01-01"

# Replace PLACEHOLDER_KV_ID and PLACEHOLDER_PREVIEW_KV_ID with actual KV namespace IDs.
# Create them with: npx wrangler kv namespace create WEBRING
[[kv_namespaces]]
binding = "WEBRING"
id = "a81c3dd88c5445c2b75c4ba51d091750"
preview_id = "01172bfbf4c34fcda8ba59b2b64daf92"

[assets]
directory = "public"

[triggers]
crons = ["0 0 * * *", "0 0 * * SUN"]
